version: '3'
services:
  web_app:
    build:
      context: ../
      dockerfile: docker/web_app/Dockerfile
    image: web_app
    container_name: web_app_container
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    image: db
    container_name: db_container
    environment:
      POSTGRES_USER: aizek
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: quizzes
    ports:
      - 5433:5432
